FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_API_URL=http://api.chronos.local
ENV VITE_API_URL=$VITE_API_URL

COPY package.json package-lock.json nx.json tsconfig.base.json ./
COPY apps ./apps
COPY libs ./libs
COPY prisma ./prisma

RUN npm ci
RUN npx nx build web --configuration=production

FROM nginx:1.27-alpine AS runtime

WORKDIR /usr/share/nginx/html

COPY apps/web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/apps/web ./

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
